name: Artifacts Example

on: [push, workflow_dispatch]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - name: Run calculation
        shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from job 1
        uses: actions/download-artifact@v5
        with:
          name: homework_pre
      - name: Multiply value
        shell: bash
        run: |
          value=$(cat math-homework.txt)
          expr $value \* 9 > math-homework.txt
      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: homework_final
          path: math-homework.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download final artifact
        uses: actions/download-artifact@v5
        with:
          name: homework_final
      - name: Show result
        shell: bash
        run: |
          value=$(cat math-homework.txt)
          echo "The final result is $value"
