name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # rulează doar pe branch-ul main
  workflow_dispatch: # permite rularea manuală

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. Login în Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t mydockeruser/my-app:latest .

      # 4. Push Docker image
      - name: Push Docker Image
        run: |
          docker push mydockeruser/my-app:latest
