name: Redis Example

on:
  workflow_dispatch:

jobs:
  test-redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0
        ports:
          - 6379:6379
        command: ["redis-server", "--requirepass", "mysecretpassword"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Test Redis connection
        run: redis-cli -a mysecretpassword ping
