name: Redis Example

on:
  workflow_dispatch:  # rulează manual
  push:
    branches:
      - main

jobs:
  test-redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0  # imagine oficială Redis
        ports:
          - 6379:6379
        options: > 
          --requirepass mysecretpassword  # optional: parola Redis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Redis CLI
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Test Redis connection
        run: |
          redis-cli -h 127.0.0.1 -p 6379 ping
